### ISSUE TITLE
Use of buttons instead of regular links

### ISSUE THREAD

**Issue by willococa** [JuniorGarciaRodriguez/ptfl-w1d3#7]
As recommended for some experts on usability I will suggest you to consider this:
- Use buttons when the user- action causes a change in either back-end or the front-end of the website. For example, submitting a form, opening a pop-up or a modal or a pannel on the same page.
- Use links when the user-action doesn’t affect the website at all. In this, the users are just readers or spectators of the site. For example, to navigate to the next page or an external source after viewing the content of the page.
Source:
https://www.digitala11y.com/links-vs-buttons-a-perennial-problem/#:~:text=Use%20buttons%20when%20the%20user,or%20spectators%20of%20the%20site.

**Comment by JuniorGarciaRodriguez** [comment]
Interactions will be implemented in the Javascript block and changes will be made if required. Thank you
